spring:
  application:
    name: my-service

my-service:
  message: "hello"
  yourName: "tests"

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: false
  endpoint:
    shutdown:
      enabled: false
    refresh:
      enabled: true