spring:
  application:
    name: my-service

my-service:
  message: "hello"
  yourName: "prod"

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: false
  endpoint:
    shutdown:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true

